version: '2.3'
services:
  jenkins-master:
    build: ./jenkins/
    container_name: jenkins-master
    ports:
    - 80:8080
    volumes:
    - ./data/jenkins_home:/var/jenkins_home
    - /etc/localtime:/etc/localtime
    networks:
      - jenkins

networks:
  jenkins:
          external: true
